/* Autogenerated by png2wx.pl on Wed May 21 01:56:08 2014 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_rtlsdr;

#endif /* ICONS_H */
